version: '3.8'
services:
  saturn-mssql:
    build: mssql/.
    hostname: mssql
    ports:
      - '1433:1433'
    volumes:
      - saturn-db:/var/opt/mssql
    networks:
      - saturn-net
networks:
  saturn-net:
    driver: bridge
volumes:
  saturn-db: