spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/saturn_management
    username: saturn
    password: saturn
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      additional-paths:
        - src/main/java/
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: saturn_management
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    default-schema: saturn_management
server:
  servlet:
    context-path: "/api"
  port: 8200
