spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=saturn_portal;encrypt=true;trustServerCertificate=true;
    username: saturn_portal
    password: saturn.PW
  devtools:
    livereload:
      port: 35731
    restart:
      additional-paths:
        - src/main/java/
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    user: saturn_portal
    password: saturn.PW
server:
  servlet:
    context-path: "/api"
  port: 8300
