openapi: 3.0.3
info:
  title: Saturn
  description: This is the API description of the 'portal-backend' module of the Saturn educational portal.
  version: 0.0.1
servers:
  - url: http://localhost:8300/api
    description: Local environment
paths: { }